server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  application:
    name: service-mybatisPlus

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: false
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false


logging:
  level:
    com.demo.dao: debug
